import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
import { Toaster } from 'sonner'
import "./globals.css";
import ReduxProvider from "@/components/Provider";

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700', "100", "300"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReduxProvider>
          <Header />
          <main className="main">
            <Container>
              {children}
            </Container>
          </main>
          <Footer />
          <Toaster position="bottom-center" />
        </ReduxProvider>
      </body>
    </html>
  );
}
